# Generated by Django 5.2.7 on 2026-07-26 21:51

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def populate_product_slugs(apps, schema_editor):
    """Génère un slug unique pour chaque produit déjà existant en base"""
    Product = apps.get_model('shop', 'Product')
    seen = set()
    for product in Product.objects.all():
        base = slugify(product.name) or f"produit-{product.pk}"
        candidate = base
        i = 1
        while candidate in seen or Product.objects.filter(slug=candidate).exclude(pk=product.pk).exists():
            i += 1
            candidate = f"{base}-{i}"
        product.slug = candidate
        seen.add(candidate)
        product.save(update_fields=['slug'])


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    # Run without transaction so we can create/drop indexes safely
    atomic = False

    dependencies = [
        ('shop', '0003a_remove_product_slug_conflicts'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantityDiscountRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.PositiveIntegerField(unique=True, verbose_name="Quantité minimum d'articles")),
                ('discount_percent', models.PositiveIntegerField(verbose_name='Réduction (%)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Règle de réduction par quantité',
                'verbose_name_plural': 'Règles de réduction par quantité',
                'ordering': ['min_quantity'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='gender',
            field=models.CharField(choices=[('women', 'Femme'), ('men', 'Homme'), ('unisex', 'Unisexe')], default='unisex', help_text="Utilisé pour les blocs 'Shop by Gender' de la page d'accueil", max_length=10, verbose_name='Genre principal'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, verbose_name='Réduction quantité appliquée (%)'),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='base_notes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Notes de fond'),
        ),
        migrations.AddField(
            model_name='product',
            name='concentration',
            field=models.CharField(choices=[('edp', 'Eau de Parfum'), ('edt', 'Eau de Toilette'), ('oil', 'Huile de Parfum'), ('extrait', 'Extrait de Parfum')], default='edp', max_length=10, verbose_name='Concentration'),
        ),
        migrations.AddField(
            model_name='product',
            name='concentration_percent',
            field=models.CharField(blank=True, help_text='Ex: 18%', max_length=20, null=True, verbose_name='% de concentration'),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('women', 'Femme'), ('men', 'Homme'), ('unisex', 'Unisexe')], default='unisex', max_length=10, verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='product',
            name='heart_notes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Notes de cœur'),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients_highlight',
            field=models.CharField(blank=True, help_text='Ex: Vegan, Cruelty-free, Sans paraben', max_length=255, null=True, verbose_name='Ingrédients clés'),
        ),
        migrations.AddField(
            model_name='product',
            name='inspired_by',
            field=models.CharField(blank=True, help_text='Ex: Baccarat Rouge 540 - Maison Francis Kurkdjian', max_length=200, null=True, verbose_name='Inspiré de (marque de luxe)'),
        ),
        migrations.AddField(
            model_name='product',
            name='intensity',
            field=models.CharField(blank=True, choices=[('soft', 'Douce'), ('significant', 'Significative'), ('statement', 'Affirmée')], max_length=15, null=True, verbose_name='Intensité du parfum'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_bestseller',
            field=models.BooleanField(default=False, verbose_name='Badge Bestseller'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Badge Nouveauté'),
        ),
        migrations.AddField(
            model_name='product',
            name='luxury_price_reference',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Sert à calculer l'économie affichée sur la fiche produit", max_digits=10, null=True, verbose_name='Prix de la marque de luxe équivalente'),
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Laisser vide si le produit n'est pas en promotion", max_digits=10, null=True, verbose_name='Ancien prix (barré)'),
        ),
        migrations.AddField(
            model_name='product',
            name='scent_family',
            field=models.CharField(blank=True, choices=[('floral', 'Fleuri'), ('fresh', 'Frais'), ('gourmand', 'Gourmand'), ('herbal', 'Herbacé'), ('earthy', 'Terreux'), ('warm', 'Chaud')], max_length=20, null=True, verbose_name='Famille olfactive'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, null=True),
        ),
        migrations.RunPython(populate_product_slugs, reverse_noop),
        # Create a unique index on slug using a deterministic name to avoid
        # collisions with auto-generated index names in different environments.
        migrations.RunSQL(
            """
            DROP INDEX IF EXISTS public.shop_product_slug_unique;
            CREATE UNIQUE INDEX shop_product_slug_unique ON public.shop_product (slug);
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name='product',
            name='top_notes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Notes de tête'),
        ),
        migrations.AddField(
            model_name='product',
            name='volume_ml',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Contenance (ml)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/', verbose_name='Image principale'),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product')),
            ],
            options={
                'verbose_name': 'Image de galerie',
                'verbose_name_plural': 'Images de galerie',
                'ordering': ['order'],
            },
        ),
    ]
