# Generated by Django 5.2.7 on 2026-07-26 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_quantitydiscountrule_category_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_video', models.FileField(blank=True, help_text='Format MP4 recommandé, quelques secondes en boucle, poids léger (< 10 Mo idéalement).', null=True, upload_to='site/', verbose_name="Vidéo de fond (page d'accueil)")),
                ('hero_video_url', models.URLField(blank=True, help_text='Si rempli, prioritaire sur le fichier uploadé ci-dessus.', null=True, verbose_name='OU lien vidéo externe (Cloudinary, YouTube-mp4, etc.)')),
            ],
            options={
                'verbose_name': 'Réglages du site',
                'verbose_name_plural': 'Réglages du site',
            },
        ),
    ]
