# Generated by Django 5.2.7 on 2026-08-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='gender_image_men',
            field=models.ImageField(blank=True, help_text='Format portrait recommandé (ratio 3:4). Si vide, une image générique est utilisée.', null=True, upload_to='site/', verbose_name='Photo bloc Homme'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gender_image_unisex',
            field=models.ImageField(blank=True, help_text='Format portrait recommandé (ratio 3:4). Si vide, une image générique est utilisée.', null=True, upload_to='site/', verbose_name='Photo bloc Unisexe'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gender_image_women',
            field=models.ImageField(blank=True, help_text='Format portrait recommandé (ratio 3:4). Si vide, une image générique est utilisée.', null=True, upload_to='site/', verbose_name='Photo bloc Femme'),
        ),
    ]
