# Generated by Django 5.2.7 on 2026-08-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_sitesettings_gender_image_men_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inscrit newsletter',
                'verbose_name_plural': 'Inscrits newsletter',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
