"""
Django settings for katauparfum project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-@&oow3t&6&@+j0y)5i!(@xg_qsy7@0l=ncp@z)r7%=d5bjpy!1')

# SECURITY WARNING: don't run with debug turned on in production!
# Sur LWS, vous pourrez définir la variable d'environnement DEBUG à 'False'
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['*']

# Configuration Render automatique pour la sécurité (CSRF)
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS = [f'https://{RENDER_EXTERNAL_HOSTNAME}']

# Indispensable pour Render : permet à Django de savoir qu'il est en HTTPS derrière le proxy
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'cloudinary_storage',  # Gestion stockage Cloudinary
    'cloudinary',          # Librairie Cloudinary
    'jazzmin',  # Django Jazzmin - Admin luxe & moderne
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shop',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'katauparfum.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'django.template.context_processors.csrf',
                'django.template.context_processors.static',
                'shop.context_processors.currency',
                'shop.context_processors.whatsapp_config',
            ],
        },
    },
]

WSGI_APPLICATION = 'katauparfum.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Configuration intelligente : PostgreSQL sur Render, SQLite en local
DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///' + str(BASE_DIR / 'db.sqlite3'),
        conn_max_age=600
    )
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Gestion des fichiers statiques en production (WhiteNoise)
STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Empêcher le plantage si un fichier source map est manquant (ex: Jazzmin bootstrap.map)
WHITENOISE_MANIFEST_STRICT = False

# ⚠️ COMPATIBILITÉ DJANGO 6.0 : Ces réglages sont requis par la librairie Cloudinary
# qui cherche encore les anciennes variables supprimées dans Django 5+
STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"
DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Configuration Cloudinary (Images produits)
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME', "").strip(),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY', "").strip(),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET', "").strip(),
}

# Session configuration
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 2592000  # 30 days
SESSION_COOKIE_HTTPONLY = True
SECURE_SSL_REDIRECT = False

# Security (adjust for production)
# CSRF_TRUSTED_ORIGINS = []

# WhatsApp Configuration
WHATSAPP_ADMIN_PHONE = '+22896084619'


# ========================================
# DJANGO JAZZMIN - Admin Premium Luxe
# ========================================
JAZZMIN_SETTINGS = {
    # Titre et branding
    "site_title": "KAT AU PARFUM",
    "site_header": "💎 KAT AU PARFUM - Admin",
    "site_brand": "KAT AU PARFUM",
    "welcome_sign": "Bienvenue à l'Administration Luxe KAT AU PARFUM 💎",
    
    # Icônes & Logos
    "site_logo": "img/logo.png",
    "site_logo_classes": "img-fluid",
    "site_icon": "img/favicon.png",
    
    # Couleurs theme
    "theme": "default",
    "user_avatar": None,
    
    # Configuration de la sidebar
    "show_sidebar": True,
    "navigation_expanded": True,
    
    # Order de la navigation (optionnel)
    "order_with_respect_to": ["shop", "auth"],
    
    # Filtres & Actions
    "show_search": True,
    "search_model_preview": True,
    
    # Responsive
    "responsive_admin": True,
    
    # Icones personnalisés pour le menu
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "shop.category": "fas fa-tags",
        "shop.product": "fas fa-gem",
        "shop.order": "fas fa-shopping-bag",
        "shop.orderitem": "fas fa-cart-plus",
    },
    
    # Couleurs personnalisées
    "default_icon_parents": "fas fa-chevron-right",
    "default_icon_children": "fas fa-arrow-right",
    
    # Comportement
    "useable_permissions": ["auth.add_user", "auth.change_user", "auth.delete_user"],
    "hide_apps": [],
    
    # Footer
    # UI builder (customizer) is entirely disabled; prevents cog/toggle rendering
    "show_ui_builder": False,
    
    # CSS personnalisé
    "custom_css": "css/jazzmin_custom.css",
    "custom_js": "js/custom_admin.js",
    
    # Related Modal
    "related_modal_active": True,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small": False,
    "footer_small": False,
    "body_small": False,
    "sign_in_maximize": False,
    "windows_overlapped_behavior": True,
    "navbar_fixed": True,
    "presized_sidebar_menu": False,
    "navbar_color": "#1a1a1a",
    "navbar_text_color": "#d4af37",
    "navbar_small_text": True,
    "navbar_variant": "dark",
    "body_bg": "linear-gradient(135deg, #faf8f3 0%, #f4ede4 100%)",
    "sidebar_bg": "linear-gradient(135deg, #1a1a1a 0%, #2d2d2d 100%)",
    "sidebar_text_color": "#d4af37",
    "sidebar_nav_small_text": True,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_fixed": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
}
